### ISSUE TITLE
BulkData Export produces FHIROperationException

### ISSUE THREAD

**Issue by corneliusknopp** [IBM/FHIR#1336]
**Describe the bug**
When using the `fhir-operation-bulkdata` module within my IBM FHIR Server by accessing the URL `url:9080/$export` (no matter if with or without Query-Parameters), the Response is a simple `FHIROperationException: Error while processing the $export request`.
The Logs only contain the same Error Message, but no stacktrace or other hints on the error-source.
Is there a special log for the bulkdata-module?

**To Reproduce**
1. `curl -k -u "fhiruser:change-password" -H "Content-Type: application/fhir+json" -X GET 'http://localhost:9080/fhir-server/api/v4/$export?_outputFormat=application/fhir%2Bndjson&_type=Patient' -v` 
or alternatively using Postman
2. See error

**Expected behavior**
Should export the content to COS or at least show more usefull error messages.

**Additional context**
I'm using IBM FHIR 4.3.0 in combination with PostgreSQL via Docker-Compose. In Order to enable the bulkdata-module, i configured the files `configDropins/defaults/bulkdata.xml`, `/config/default/fhir-server-config.json`, and `server.xml` according to the [Guide](https://ibm.github.io/FHIR/guides/FHIRBulkOperations/).

**Comment by corneliusknopp** [comment]
Possibly related to Issue #1161 (at least wider `OperationOutcome`s could give hints on the error-source)

**Comment by prb112** [comment]
There are two locations to look for log files: 
fhir-server/logs/ which has messages.log and trace.log 

trace.log is populated when you change your server.xml to add the following:
`<logging traceFormat="BASIC" traceSpecification="*=info:com.ibm.fhir.*=finest"/>`

You should not run with the traceSpecification `com.ibm.fhir.*=finest` in production.

The second spot is related to JavaBatch. in the fhir-server/logs folder you'll see another folder joblogs, and you'll navigate down to the date folder `fhir-server/logs/joblogs/bulkexportchunkjob/2020-07-17`.  That will have even more information.  If the request succeeded to generate the java batch job.

Regarding the comment, #1161 is not directly related, it's on the javabatch operationoutcomes when acting on the import or export data.  What you are seeing is the Operation failing which mediates the interaction between the REST operation and the JavaBatch.  

If you can grab the trace.log, I can help you figure out the issue.  Right now it looks like it's in the creation of the job that is failing.

**Comment by corneliusknopp** [comment]
my `fhir-server/logs/` folder only contains `state/com.ibm.ws.jmx.local.address` and `state/plugin-cfg.xml`

Does the logging-configuration above belong underneath the `<server drescription="fhir-server">` tag in `server.xml`?

**Comment by prb112** [comment]
Yes, under server.xml (it's actually commented out in the default server.xml as an example)
in the case of fhir-server/logs the default is to log out to the docker console, if you enable the trace.log, you should see that folder populated.  (I think on some docker containers, it might be mapped from `/logs`

**Comment by prb112** [comment]
Hi @corneliusknopp checking in... were you able to get your issue addressed with the additional logs?

**Comment by prb112** [comment]
Moved to Review/QA (will close at end-of-iteration).

**Comment by corneliusknopp** [comment]
I've not managed to populate either `messages.log` or `trace.log`.
The given line (`<logging traceFormat="BASIC" traceSpecification="*=info:com.ibm.fhir.*=finest"/>`) does not make any difference.

Within the Docker Logs i've found the following Warnings regarding `bulkdata`:
```[WARNING ] CWNEN0047W: Resource annotations on the fields of the com.ibm.fhir.jbatch.bulkdata.export.group.ChunkReader class will be ignored. The annotations could not be obtained because of the exception : java.lang.NoClassDefFoundError: com.ibm.fhir.exception.FHIRException
[WARNING ] CWNEN0048W: Resource annotations on the fields of the com.ibm.fhir.jbatch.bulkdata.export.patient.ChunkReader class will be ignored. The com.ibm.fhir.jbatch.bulkdata.export.patient.ChunkReader class is being processed for annotations because it is referenced by the com.ibm.fhir.jbatch.bulkdata.export.group.ChunkReader application class. The annotations could not be obtained because of the exception : java.lang.NoClassDefFoundError: com.ibm.fhir.exception.FHIRException
[WARNING ] CWNEN0049W: Resource annotations on the methods of the com.ibm.fhir.jbatch.bulkdata.export.group.ChunkReader class will be ignored. The annotations could not be obtained because of the exception : java.lang.NoClassDefFoundError: com.ibm.fhir.exception.FHIRException
[WARNING ] CWNEN0047W: Resource annotations on the fields of the com.ibm.fhir.jbatch.bulkdata.export.system.ChunkReader class will be ignored. The annotations could not be obtained because of the exception : java.lang.NoClassDefFoundError: com.ibm.fhir.exception.FHIRException
[WARNING ] CWNEN0049W: Resource annotations on the methods of the com.ibm.fhir.jbatch.bulkdata.export.system.ChunkReader class will be ignored. The annotations could not be obtained because of the exception : java.lang.NoClassDefFoundError: com.ibm.fhir.exception.FHIRException
[WARNING ] CWNEN0047W: Resource annotations on the fields of the com.ibm.fhir.jbatch.bulkdata.load.ChunkWriter class will be ignored. The annotations could not be obtained because of the exception : java.lang.NoClassDefFoundError: com.ibm.fhir.exception.FHIRException
[WARNING ] CWNEN0049W: Resource annotations on the methods of the com.ibm.fhir.jbatch.bulkdata.load.ChunkWriter class will be ignored. The annotations could not be obtained because of the exception : java.lang.NoClassDefFoundError: com.ibm.fhir.exception.FHIRException
[WARNING ] CWNEN0047W: Resource annotations on the fields of the com.ibm.fhir.jbatch.bulkdata.export.patient.ChunkReader class will be ignored. The annotations could not be obtained because of the exception : java.lang.NoClassDefFoundError: com.ibm.fhir.exception.FHIRException
[WARNING ] CWNEN0049W: Resource annotations on the methods of the com.ibm.fhir.jbatch.bulkdata.export.patient.ChunkReader class will be ignored. The annotations could not be obtained because of the exception : java.lang.NoClassDefFoundError: com.ibm.fhir.exception.FHIRException```

Besides this, there are some Warnings on missing `derbyLocale_XX_XX.jar` within `fhir-server-webapp.war/WEB-INF/lib/...` which should not affect the functionality as PostgreSQL is used.

**Comment by prb112** [comment]
The derbyLocale warnings are expected as we do not bundle the locale jars.  This is a benign warning. 
The logs indicate you are missing a fhir-config entry. 

Are you on the 4.4.0 release? I'd suggest moving up to the latest release. As it sounds like you have an older version on searching the annotations (note that above is just a warning).

**Comment by corneliusknopp** [comment]
1) ok, so the derbyLocale warnings can be ignored

2) Missing entry within `fhir-server-config.json` ? I pasted the bulkdata Configuration into the 2nd leven (same level as core, audit & persistence)

3) I've already moved on to version 4.3.3 

The Error when running the curl-command of original post is still present. 
There is no `messages.log` or `trace.log` created which i could send to you.

**Comment by prb112** [comment]
The warning above was a missing Annotation in the javacode that produces that warning. It was fixed in an earlier version maybe 4.2.*, it shouldn't be there in 4.3.3. 

If you are using the docker image, are you checking /logs ?

**Comment by prb112** [comment]
I'd be happy to do a screenshare and diagnose with you next week, you can ping me on Zulip - https://chat.fhir.org/#narrow/stream/212434-ibm

**Comment by corneliusknopp** [comment]
> If you are using the docker image, are you checking /logs ?

Do you mean `/opt/ol/wlp/usr/servers/fhir-server/logs/`?
There is only the `state/` folder containing `com.ibm.ws.jmx.local.address` & `plugin-cfg.xml`. Nothing else.

Or do you mean the `docker logs` for the FHIR-Container?


> I'd be happy to do a screenshare and diagnose with you next week, you can ping me on Zulip - https://chat.fhir.org/#narrow/stream/212434-ibm

Thank you! I will do this.

**Comment by prb112** [comment]
We remap the logs to `/logs` if you check there the logs should be in that folder. 

Yes, please reach out, I'm a bit preoccupied this week, but would be happy to work with you. 

@lmsurpre also might be available.
